---
- name: '-'
  hosts: all
  gather_facts: false
  become_method: sudo

  pre_tasks:
    - name: 'Connect to host & retrieve facts'
      ansible.builtin.setup:
        gather_subset:
          - '!all'
          - 'network'

  tasks:
    - import_tasks: tasks/uninstall.yml
    - import_tasks: tasks/install_pip.yml
    - import_tasks: tasks/install_pipx.yml

# list commands to run
